# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2a1e4d090063f8b84f17a78fe061fd636b28106bc3a7b8b1a22e08c9b238eddec81f425b03184238ec18c877ab6fc828cece12ff7e9503fbdab5d45fd9f713b

test:
  secret_key_base: 34d570a20285ab3337e458b305eea27c8771d52a4ddcdcc51a625e2e52e9c4662f5ca98d6cb0f22f23c653e3eb44af4bf24e3cdb73080f71a8cd7e006e95d406

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
